/* Editorial data — single source for articles + recipes (used by homepage strip,
   list pages, and detail pages). Bilingual where it earns it. */

const ARTICLES = [
  {
    slug: "the-stone-and-the-curd",
    kind: "essay",
    category: "Heritage",
    title: "The stone, the curd, and two thousand years",
    dek: "Why the cheese in your kitchen has roots older than Rome — and what an Ohio creamery owes to a village in Samegrelo.",
    author: "Nino Beridze",
    date: "May 4, 2026",
    readMin: 12,
    hero: "stone-press",
    feature: "large",
  },
  {
    slug: "pop-up-german-village",
    kind: "news",
    category: "Updates",
    title: "Pop-up Saturday — German Village Farmers' Market",
    dek: "We'll be at the corner of Mohawk and Frankfort with hot adjaruli and 200 wheels of fresh sulguni. Get there early.",
    author: "The Bakery",
    date: "May 2, 2026",
    readMin: 2,
    hero: "market-stall",
  },
  {
    slug: "milk-of-three-rivers",
    kind: "essay",
    category: "Sourcing",
    title: "The milk of three rivers",
    dek: "We drive to three Ohio dairies every morning before sunrise. Here is why none of them are bigger than 80 cows.",
    author: "Levan T.",
    date: "Apr 28, 2026",
    readMin: 8,
    hero: "dairy",
  },
  {
    slug: "khachapuri-explained",
    kind: "essay",
    category: "Field Notes",
    title: "A field guide to khachapuri",
    dek: "Adjaruli, Imeruli, Megruli, Penovani, Ossuri — five breads, five regions, one country. A primer for first-timers.",
    author: "Nino Beridze",
    date: "Apr 22, 2026",
    readMin: 9,
    hero: "khachapuri-flat",
  },
  {
    slug: "eater-midwest-feature",
    kind: "news",
    category: "Press",
    title: "Eater Midwest names us a 'best new bakery'",
    dek: "We are stunned and grateful. Read Brett Anderson's piece on what is happening on Tuller Road this spring.",
    author: "Press desk",
    date: "Apr 18, 2026",
    readMin: 3,
    hero: "press-clipping",
  },
  {
    slug: "supra-at-home",
    kind: "essay",
    category: "Heritage",
    title: "How to set a supra at home",
    dek: "The Georgian feast is a structure, not a menu. Toasts, tamada, and the order of the table — for a Tuesday in Ohio.",
    author: "Mariam K.",
    date: "Apr 14, 2026",
    readMin: 11,
    hero: "supra",
  },
  {
    slug: "sulguni-vs-mozzarella",
    kind: "essay",
    category: "Field Notes",
    title: "Sulguni is not mozzarella, exactly",
    dek: "They are cousins from the same pasta-filata family — pulled, stretched, brined. Here is what makes them different.",
    author: "Nino Beridze",
    date: "Apr 8, 2026",
    readMin: 7,
    hero: "sulguni-section",
  },
  {
    slug: "wholesale-launch",
    kind: "news",
    category: "Updates",
    title: "Wholesale program is open for Spring 2026",
    dek: "Restaurants, grocers, and caterers in OH/MI/IN/PA/KY: we are accepting accounts. Sample boxes ship Mondays.",
    author: "The Bakery",
    date: "Apr 1, 2026",
    readMin: 4,
    hero: "wholesale-crate",
  },
];

const RECIPES = [
  {
    slug: "adjaruli-at-home",
    title: "Adjaruli khachapuri, weekend project",
    ka: "აჭარული ხაჭაპური",
    cuisine: "Traditional",
    diet: ["Vegetarian"],
    time: 180,
    timeLabel: "3 hours",
    difficulty: "Project",
    serves: 4,
    note: "The boat-shaped one. Yeasted dough, sulguni and imeruli inside, an egg yolk and a pat of butter on top.",
    feature: true,
    pairing: "Sulguni Fresh + Imeruli",
  },
  {
    slug: "imeruli-quick",
    title: "Imeruli khachapuri, on a Tuesday",
    ka: "იმერული ხაჭაპური",
    cuisine: "Traditional",
    diet: ["Vegetarian", "Quick"],
    time: 45,
    timeLabel: "45 min",
    difficulty: "Easy",
    serves: 4,
    note: "Round, stuffed with cheese, no yeast. The version Georgians actually make on a weeknight.",
    pairing: "Imeruli + Sulguni Aged",
  },
  {
    slug: "sulguni-grilled-cheese",
    title: "Sulguni grilled cheese, with walnut",
    ka: "",
    cuisine: "Modern",
    diet: ["Vegetarian", "Quick"],
    time: 15,
    timeLabel: "15 min",
    difficulty: "Easy",
    serves: 2,
    note: "Three things: sulguni, sourdough, a spoon of walnut tkemali. The best lunch you'll make this month.",
    pairing: "Sulguni Fresh",
  },
  {
    slug: "lobio-pot",
    title: "Lobio — red bean stew with adjika",
    ka: "ლობიო",
    cuisine: "Traditional",
    diet: ["Vegan", "Gluten-free"],
    time: 90,
    timeLabel: "1.5 hours",
    difficulty: "Easy",
    serves: 6,
    note: "Red kidney beans, walnut, marigold, coriander. We eat it with mchadi corn cakes and a wedge of imeruli.",
    pairing: "Imeruli on the side",
  },
  {
    slug: "khinkali-bites",
    title: "Khinkali — soup dumplings, the Tbilisi way",
    ka: "ხინკალი",
    cuisine: "Traditional",
    diet: [],
    time: 120,
    timeLabel: "2 hours",
    difficulty: "Project",
    serves: 4,
    note: "Pleated dumplings full of broth and beef. Pinch the top, hold the topknot, do not let the soup escape.",
  },
  {
    slug: "ojakhuri-skillet",
    title: "Ojakhuri — pork & potatoes, one skillet",
    ka: "ოჯახური",
    cuisine: "Traditional",
    diet: ["Gluten-free"],
    time: 60,
    timeLabel: "1 hour",
    difficulty: "Easy",
    serves: 4,
    note: "Family-style. Pork shoulder, golden potatoes, tons of cilantro and red onion at the end.",
  },
  {
    slug: "sulguni-cornbread",
    title: "Mchadi — corn bread, sulguni inside",
    ka: "მჭადი",
    cuisine: "Traditional",
    diet: ["Vegetarian", "Gluten-free", "Quick"],
    time: 25,
    timeLabel: "25 min",
    difficulty: "Easy",
    serves: 4,
    note: "Cornmeal cakes pan-fried in butter with a slab of sulguni melted into the middle. A breakfast or a side.",
    pairing: "Sulguni Fresh",
  },
  {
    slug: "khachapuri-bites",
    title: "Khachapuri party bites, 30 minutes",
    ka: "",
    cuisine: "Modern",
    diet: ["Vegetarian", "Quick"],
    time: 30,
    timeLabel: "30 min",
    difficulty: "Easy",
    serves: 8,
    note: "Puff pastry squares, sulguni and imeruli, an egg wash. Trays of these for any party, any holiday.",
    pairing: "Sulguni + Imeruli",
  },
  {
    slug: "pkhali-trio",
    title: "Pkhali — three walnut spreads",
    ka: "ფხალი",
    cuisine: "Traditional",
    diet: ["Vegan", "Gluten-free"],
    time: 60,
    timeLabel: "1 hour",
    difficulty: "Medium",
    serves: 6,
    note: "Spinach, beet, and red bean — each pounded with walnuts, garlic, and marigold. The Georgian welcome plate.",
  },
  {
    slug: "shredded-pasta-bake",
    title: "Sulguni-shred pasta, baked",
    ka: "",
    cuisine: "Modern",
    diet: ["Vegetarian"],
    time: 50,
    timeLabel: "50 min",
    difficulty: "Easy",
    serves: 6,
    note: "Our shredded imeruli was made for this. Pasta, tomato, lots of melted shred, baked till bubbling.",
    pairing: "Shredded Imeruli",
  },
  {
    slug: "holiday-supra-spread",
    title: "Holiday supra — a Georgian feast plan",
    ka: "სუფრა",
    cuisine: "Holiday",
    diet: [],
    time: 480,
    timeLabel: "all day",
    difficulty: "Project",
    serves: 12,
    note: "A full menu for 12: pkhali, lobio, khachapuri, ojakhuri, walnut sauces, and the toasts that hold it together.",
  },
  {
    slug: "easter-paska",
    title: "Easter paska, with sulguni twist",
    ka: "",
    cuisine: "Holiday",
    diet: ["Vegetarian"],
    time: 240,
    timeLabel: "4 hours",
    difficulty: "Project",
    serves: 8,
    note: "A bread that sits on the holiday table for a week. Ours folds in a layer of sulguni and a swirl of saffron.",
  },
];

window.ARTICLES = ARTICLES;
window.RECIPES = RECIPES;
